dist: trusty
language: java
jdk: oraclejdk8
services:
  - docker
# test definition  
#before_script:
#  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || [ "${TRAVIS_BRANCH}" != "main" ] || docker login -u springbuildmaster -p "$DOCKERHUB_PASSWORD"'
script:
  - ./mvnw spring-boot:build-image -D spring-boot.build-image.imageName=springio/petclinic
